{% set name = "util-linux" %}
{% set version = "2.39.3" %}
{% set major_minor = '.'.join(version.split('.')[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v{{ major_minor }}/util-linux-{{ version }}.tar.xz
  sha256: 7b6605e48d1a49f43cc4b4cfc59f313d0dd5402fa40b96810bd572e167dfed0f

build:
  number: 1
  skip: true  # [not unix]
  run_exports:
    - {{ pin_subpackage('util-linux', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - sysroot_linux-64  2.17  # [linux64]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
    - libtool
    - autoconf
    - automake
    - pkg-config
  host:
    - python 3.12
    - zlib
    - ncurses
    - readline
    - libuuid
    - libxcrypt  # [linux]
  run:
    - python

test:
  commands:
    - test -f "${PREFIX}/lib/libmount.so"  # [linux]
    - test -f "${PREFIX}/bin/hexdump"

about:
  home: https://en.wikipedia.org/wiki/Util-linux
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A random collection of Linux utilities
  dev_url: https://github.com/util-linux/util-linux

extra:
  recipe-maintainers:
    - jaimergp
    - scopatz
    - hmaarrfk
# Exclude Windows and macOS
build:
  skip: true  # [win or osx]
