package:
  name: lvm2
  version: 2.03.23

source:
  url: https://sourceware.org/ftp/lvm2/LVM2.2.03.23.tgz
  md5: 0535b5e638b6f0b48f7b259e0ec0ba65

requirements:
  build:
    - {{ compiler('c') }}
    - pkgconfig
  host:
    - libaio
    - readline

test:
  commands:
    - lvm --help

about:
  home: https://sourceware.org/lvm2/
  license:  BSD 2-Clause "Simplified" License.
