package:
  name: libiconv
  version: "1.17"

source:
  url: https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz
  sha256: 8f74213b56238c85a50a5329f77e06198771e70dd9a739779f4c02f65d971313 

requirements:
  build:
    - {{ compiler('c') }}
    - python 3.12

test:
  commands:
    - iconv --help

about:
  home: https://www.gnu.org/software/libiconv/
  summary: This library provides an iconv() implementation, for use on systems which don't have one, or whose implementation cannot convert from/to Unicode.
  license: GPL AND LGPL
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - Geertsky
