package:
  name: libiconv
  version: "1.17"

source:
  url: https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz
  sha256: 8f74213b56238c85a50a5329f77e06198771e70dd9a739779f4c02f65d971313 

requirements:
  build:
    - {{ compiler('c') }}
    - python 3.12

test:
  commands:
    - iconv --help

about:
  home: https://www.gnu.org/software/libiconv/
  license: LGPL
# Exclude Windows and macOS
build:
  skip: true  # [win or osx]
