# ------------------------------------------------
package:
    name: gtk-doc
    version: "1.34.0"
source:
  url: https://download.gnome.org/sources/gtk-doc/1.34/gtk-doc-1.34.0.tar.xz
  md5: f0e7385ba25eddb6ce0953e8cf63d1bf
requirements:
  build:
    - {{ compiler('c') }}
    - coreutils
    - glib
    - libxml2
    - meson
    - ninja
    - pkgconfig
    - pygments
  
  host:
    - docbook-xml
    - docbook-slt-nons
    - glib
    - itstool
    - libxslt
    - libxml2
    - pygments
