package:
  name: docbook-xml
  version: "4.5"

source:
  url: https://www.docbook.org/xml/4.5/docbook-xml-4.5.zip
  md5: 03083e288e87a7e829e437358da7ef9e

requirements:
  host:
    - libxml2
    - sgml-common
    - libarchive
  build:
    - libxml2
