package:
  name: dosfstools
  version: "4.2"

source:
  url: https://github.com/dosfstools/dosfstools/releases/download/v4.2/dosfstools-4.2.tar.gz
  md5: 49c8e457327dc61efab5b115a27b087a

requirements:
  build:
    - {{ compiler('c') }}
about:
  home: https://github.com/Geertsky/dracut-bambini
  summary: dosfstools consists of the programs mkfs.fat, fsck.fat and fatlabel to create, check and label file systems of the FAT family.
  license:  GPL-3.0 license
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - Geertsky
