# ------------------------------------------------
package:
    name: libxml2
    version: "2.12.6"
source:
  url: https://download.gnome.org/sources/libxml2/2.12/libxml2-2.12.6.tar.xz
  md5: 37fab9ace78d8a085af81dc9a19f36d9
requirements:
  build:
    - {{ compiler('c') }}
    - python 3.12
  host:
    - python 3.12
    - icu
    - zlib
about:
  home: https://github.com/GNOME/libxml2
  summary: libxml2 is an XML toolkit implemented in C, originally developed for the GNOME Project.
  license: MIT
  license_file:
    - Copyright

extra:
  recipe-maintainers:
    - Geertsky
