package:
  name: parted
  version: 3.6

source:
  url: https://ftp.gnu.org/gnu/parted/parted-3.6.tar.xz
  md5: 93d2d8f22baebc5eb65b85da05a79e4e

requirements:
  host:
  - python 3.12
  build:
    - {{ compiler('c') }}
    - automake
    - autoconf
    - bc
    - check
    - gettext
    - gperf
    - gzip
    - libdevmapper
    - libtool
    - lvm2
    - make 
    - perl
    - python 3.12
    - rsync
    - tar
    - texinfo
    - util-linux
  run:
    - libiconv
    - lvm2
test:
  commands:
    - parted --help

about:
  home: http://www.gnu.org/software/parted
  license: GPL-3.0 license
  doc_url: http://www.gnu.org/software/parted/manual/parted.html
