package:
  name: zstd
  version: "1.5.6"

source:
  url: https://github.com/facebook/zstd/archive/refs/tags/v1.5.6.tar.gz
  md5: 2543d7cb3beda9ec48f965e5059dbd42

requirements:
  build:
    - {{ compiler('c') }}
# Exclude Windows and macOS
build:
  skip: true  # [win or osx]
