# ------------------------------------------------
package:
    name: kmod
    version: "32"
source:
  url: https://github.com/kmod-project/kmod/archive/refs/tags/v32.tar.gz
  md5: d4add077d68d22855082a62916d81d0e
requirements:
  build:
    - autoconf
    - automake
    - {{ compiler('c') }}
    - gtk-doc
    - libtool
    - pkgconfig
  
  host:
    - gtk-doc
    - openssl
    - xz
    - zlib
    - zstd
about:
  home: https://github.com/kmod-project/kmod
  summary: kmod is a set of tools to handle common tasks with Linux kernel modules like insert, remove, list, check properties, resolve dependencies and aliases.
  license: GPL-2.0 AND LGPL-2.1
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - Geertsky
