# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/geert/git/geertsky/dracut-bambini/conda-recipes/libffi, last modified Sun Mar 31 18:17:47 2024
# ------------------------------------------------

package:
  name: libffi
  version: 3.4.2
source:
  md5: f2e272ec793571f28d52006ad14534c4
  url: https://github.com/libffi/libffi/archive/refs/tags/v3.4.2.tar.gz
build:
  string: h9bf148f_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.71 pl5321h2b4cb7a_1
    - automake 1.16.5 pl5321ha770c72_0
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hdade7a5_3
    - gcc_impl_linux-64 13.2.0 h338b0a0_5
    - gcc_linux-64 13.2.0 h1ed452b_3
    - gettext 0.21.1 h27087fc_0
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 13.2.0 ha9c7c90_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsanitizer 13.2.0 h7e041cc_5
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libtool 2.4.7 h27087fc_0
    - libxcrypt 4.4.36 hd590300_1
    - m4 1.4.18 h516909a_1001
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
  run:
    - libgcc-ng >=13
about: {}
extra:
  copy_test_source_files: true
  final: true
