{% set version = "1.13.4" %}
{% set sha256sum = "4c93abc0bff54b296f41f92dd3aa1e73e554265a6f719df465574983ef6f878c" %}
package:
  name: automake
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/automake/automake-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    - perl 5.32.1

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - help2man
  host:
    - m4
    - autoconf
    - perl=5.32.1
    - make
  run:
    - m4
    - autoconf
    - perl=5.32.1

about:
  home: http://www.gnu.org/software/automake/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Tool for automatically generating Makefile.in files compliant with the GNU Coding Standards.
  description: |
    Automake is a tool for automatically generating Makefile.ins from files
    called Makefile.am.  It assumes that the project uses Autoconf and enforces
    certain restrictions on the configure.ac contents.
  dev_url: https://git.savannah.gnu.org/git/automake.git
  doc_url: https://www.gnu.org/software/automake/manual/automake.html
  doc_source_url: http://git.savannah.gnu.org/cgit/automake.git/tree/doc

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - mingwandroid
