# ------------------------------------------------
package:
    name: docbook-xsl-nons
    version: "1.79.2"
source:
  url: https://github.com/docbook/xslt10-stylesheets/releases/download/release/1.79.2/docbook-xsl-nons-1.79.2.tar.bz2
  md5: 2666d1488d6ced1551d15f31d7ed8c38
requirements:
  build:
    - {{ compiler('c') }}
  
  host:
    - libxml2
about:
  home: https://docbook.org/xml/4.5/
  summary: DocBook is a general purpose [XML] and [SGML] document type particularly well suited to books and papers about computer hardware and software
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - Geertsky
