package:
  name: e2fsprogs
  version: "1.47"

source:
  url: https://deac-ams.dl.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.47.0/e2fsprogs-1.47.0.tar.gz
  md5: 6b4f18a33873623041857b4963641ee9

requirements:
  host:
  build:
    - {{ compiler('c') }}
about:
  home: https://e2fsprogs.sourceforge.net/
  summary: The filesystem utilities for use with the ext2 filesystem. It also supports the ext3 and ext4 filesystems.
  license: GPL-2.0 AND LGPL-2.1

extra:
  recipe-maintainers:
    - Geertsky
