# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 12 13:38:26 2024
# ------------------------------------------------

package:
  name: pygobject
  version: 3.48.1
source:
  sha256: 3a0a2c0c0f25931b5840649c54834b9e58a63148d37fa9f6308887b7027e15c2
  url: https://download.gnome.org/sources/pygobject/3.48/pygobject-3.48.1.tar.xz
build:
  number: '0'
  string: py312h15a1d3f_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64
    - binutils_linux-64
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - gcc_impl_linux-64
    - gcc_linux-64
    - kernel-headers_linux-64
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.1 h59595ed_0
    - libffi
    - libgcc-devel_linux-64
    - libgcc-ng
    - libgomp 13.2.0 h807b86a_5
    - libnsl 2.0.1 hd590300_0
    - libsanitizer 12.3.0 h0f45ef3_5
    - libsqlite 3.45.1 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - meson 1.3.2 pyhd8ed1ab_0
    - ncurses 6.4 h59595ed_2
    - ninja 1.11.1 h924138e_0
    - openssl 3.2.1 hd590300_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - python 3.12.2 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 69.1.1 pyhd8ed1ab_0
    - sysroot_linux-64 2.12 he073ed8_17
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.2.2 hbcca054_0
    - cairo 1.18.0 h3faef2a_0
    - expat 2.6.1 h59595ed_0
    - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
    - font-ttf-inconsolata 3.000 h77eed37_0
    - font-ttf-source-code-pro 2.038 h77eed37_0
    - font-ttf-ubuntu 0.83 h77eed37_1
    - fontconfig 2.14.2 h14ed4e7_0
    - fonts-conda-ecosystem 1 0
    - fonts-conda-forge 1 0
    - freetype 2.12.1 h267a509_2
    - g-ir-build-tools 1.78.1 py312hcb69f48_1
    - g-ir-host-tools 1.78.1 hfff48b1_1
    - gettext 0.21.1 h27087fc_0
    - glib 2.78.4 hf2295e7_4
    - glib-tools 2.78.4 hde27a5a_4
    - gobject-introspection 1.78.1 py312h15a1d3f_1
    - icu 73.2 h59595ed_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libexpat 2.6.1 h59595ed_0
    - libffi
    - libgcc-ng
    - libgirepository 1.78.1 h003a4f0_1
    - libglib 2.78.4 hf2295e7_4
    - libgomp 13.2.0 h807b86a_5
    - libiconv
    - libnsl 2.0.1 hd590300_0
    - libpng 1.6.43 h2797004_0
    - libsqlite 3.45.1 h2797004_0
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - libuuid 2.38.1 h0b41bf4_0
    - libxcb 1.15 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 h59595ed_2
    - openssl 3.2.1 hd590300_0
    - pcre2 10.43 hcad00b1_0
    - pixman 0.43.2 h59595ed_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - pthread-stubs 0.4 h36c2ea0_1001
    - pycairo 1.26.0 py312he48a392_0
    - python 3.12.2 hab00c5b_0_cpython
    - python_abi 3.12 4_cp312
    - readline 8.2 h8228510_1
    - setuptools 69.1.1 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xorg-kbproto 1.0.7 h7f98852_1002
    - xorg-libice 1.1.1 hd590300_0
    - xorg-libsm 1.2.4 h7391055_0
    - xorg-libx11 1.8.7 h8ee46fc_0
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-libxext 1.3.4 h0b41bf4_2
    - xorg-libxrender 0.9.11 hd590300_0
    - xorg-renderproto 0.11.1 h7f98852_1002
    - xorg-xextproto 7.3.0 h0b41bf4_1003
    - xorg-xproto 7.0.31 h7f98852_1007
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
  run:
    - cairo >=1.18.0,<2.0a0
    - libffi >=3.4,<4.0a0
    - libgirepository
    - libglib >=2.78.4,<3.0a0
    - libiconv
    - pycairo
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  commands:
    - test -f $PREFIX/include/pygobject-3.0/pygobject.h
    - test -f `pkg-config --variable=pygobjectincludedir --dont-define-prefix pygobject-3.0`/pygobject.h
  imports:
    - gi
    - gi.pygtkcompat
    - gi.repository.GLib
  requires:
    - pkg-config
about:
  description: 'PyGObject is a Python package which provides bindings for GObject
    based libraries

    such as GTK+, GStreamer, WebKitGTK+, GLib, GIO and many more.

    '
  dev_url: https://git.gnome.org/browse/pygobject
  doc_url: https://pygobject.readthedocs.io
  home: https://pygobject.readthedocs.io
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Python bindings for GObject Introspection
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240312.1.1
  recipe-maintainers:
    - pkgw
    - ryanvolz
    - sebastian-luna-valero
    - tschoonj
  remote_url: https://github.com/conda-forge/pygobject-feedstock
  sha: 695513d4a3f7bc8ede9952c618be276b31f24ee2
# Exclude Windows and macOS
build:
  skip: true  # [win or osx]
