package:
  name: volume_key
  version: "0.3.12"

source:
  url: https://github.com/felixonmars/volume_key/archive/volume_key-0.3.12.tar.gz
  md5: d1c76f24e08ddd8c1787687d0af5a814

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - pkgconfig
    - gnupg
    - gpgme
    - libtool
    - python
  host:
    - cryptsetup
    - glib
    - gpgme
    - json-c
    - libdevmapper
    - libtool
    - nss
    - python
    - swig
    - util-linux=2.39.3=py312h40d0619_1
about:
  home: https://github.com/felixonmars/volume_key
  summary: The volume_key project provides a libvolume_key, a library for manipulating storage volume encryption keys and storing them separately from volumes, and an associated command-line tool, named volume_key.
  license: GPL-2.0
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - Geertsky
