package:
  name: cryptsetup
  version: "2.7.0"

source:
  url: https://www.kernel.org/pub/linux/utils/cryptsetup/v2.7/cryptsetup-2.7.0.tar.xz
  md5sum: 7210d45a19703bca547e8ba190278cb0


requirements:
  host:
    - libdevmapper
    - libgcrypt
    - libssh
    - libxcrypt1
    - popt
    - util-linux
    - json-c
    - openssl
  build:
    - asciidoctor
    - autoconf
    - automake
    - {{ compiler('c') }}
    - kernel-headers_linux-64
    - libtool
    - pkgconfig

test:
  commands:
    - cryptsetup --help

about:
  home: https://github.com/mbroz/cryptsetup
  license: LGPLv2.1
  doc_url: https://gitlab.com/cryptsetup/cryptsetup#documentation
