package:
  name: cryptsetup
  version: "0.1"

source:
  git_url: https://github.com/mbroz/cryptsetup.git
  git_depth: 1

requirements:
  host:
  build:
    - asciidoctor
    - autoconf
    - automake
    - {{ compiler('c') }}
    - git
    - json-c
    - kernel-headers_linux-64
    - libdevmapper
    - libgcrypt
    - libssh
    - libtool
    - libxcrypt1
    - pkgconfig
    - popt
    - util-linux
  run:
    - openssl

test:
  commands:
    - cryptsetup --help

about:
  home: https://github.com/mbroz/cryptsetup
  license: LGPLv2.1
  doc_url: https://gitlab.com/cryptsetup/cryptsetup#documentation
